using System.Text;
using DevOpsToolsInstaller.Models;

namespace DevOpsToolsInstaller.Services;

/// <summary>
/// Generates a standalone PowerShell bootstrap script that re-provisions a
/// tool set on a fresh Windows machine — no DevOpsToolsInstaller required.
/// The script downloads official vendor artifacts, extracts archives, stages
/// binaries, and launches vendor installers with an Authenticode pre-check.
/// </summary>
public static class BootstrapScriptService
{
    public static string Generate(IEnumerable<ToolDefinition> tools, string downloadsFolderHint)
    {
        var toolList = tools.OrderBy(t => t.Category).ThenBy(t => t.Name).ToList();
        var profileName = $"{Environment.MachineName} workstation - {DateTime.Now:yyyy-MM-dd}";

        var sb = new StringBuilder();
        sb.AppendLine("# DevOps Tools Installer - Workstation Bootstrap Script");
        sb.AppendLine($"# Profile : {profileName} ({toolList.Count} tools)");
        sb.AppendLine($"# Generated by DevOpsToolsInstaller v{AppUpdaterService.CurrentVersion} on {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine($"# Source downloads folder: {downloadsFolderHint}");
        sb.AppendLine();
        sb.AppendLine("<#");
        sb.AppendLine("    Rebuilds the exact tool set of the source workstation on this machine:");
        sb.AppendLine();
        sb.AppendLine("        powershell -ExecutionPolicy Bypass -File .\\bootstrap.ps1");
        sb.AppendLine();
        sb.AppendLine("    * Binary / Archive tools are staged under %LOCALAPPDATA%\\DevOpsToolsInstaller\\Tools");
        sb.AppendLine("      with executables collected into Tools\\bin (added to your user PATH).");
        sb.AppendLine("    * Installer tools (.exe / .msi) have their signature checked, then open");
        sb.AppendLine("      the vendor's own setup wizard - complete it to finish that tool.");
        sb.AppendLine("#>");
        sb.AppendLine();
        sb.AppendLine("$ErrorActionPreference = 'Stop'");
        sb.AppendLine();
        sb.AppendLine("$ToolsRoot = Join-Path $env:LOCALAPPDATA 'DevOpsToolsInstaller\\Tools'");
        sb.AppendLine("$BinFolder = Join-Path $ToolsRoot 'bin'");
        sb.AppendLine("$Downloads = Join-Path $env:TEMP 'DevOpsToolsInstaller-bootstrap'");
        sb.AppendLine("New-Item -ItemType Directory -Force -Path $ToolsRoot, $BinFolder, $Downloads | Out-Null");
        sb.AppendLine();
        sb.AppendLine("$tools = @(");
        for (int i = 0; i < toolList.Count; i++)
        {
            var tool = toolList[i];
            var name = tool.Name.Replace("'", "''");
            var url = tool.DownloadUrl.Replace("'", "''");
            var file = tool.FileName.Replace("'", "''");
            // No trailing comma on the last entry — PowerShell rejects it.
            var separator = i < toolList.Count - 1 ? "," : "";
            sb.AppendLine($"    @{{ Id='{tool.Id}'; Name='{name}'; Kind='{tool.Kind}'; Url='{url}'; File='{file}' }}{separator}");
        }
        sb.AppendLine(")");
        sb.AppendLine();
        sb.AppendLine("foreach ($tool in $tools) {");
        sb.AppendLine("    Write-Host (\"==> $($tool.Name) ($($tool.Kind))\")");
        sb.AppendLine("    $dest = Join-Path $Downloads $tool.File");
        sb.AppendLine("    if (-not (Test-Path $dest) -or (Get-Item $dest).Length -eq 0) {");
        sb.AppendLine("        Invoke-WebRequest -Uri $tool.Url -OutFile $dest -UseBasicParsing");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    switch ($tool.Kind) {");
        sb.AppendLine("        'Binary' {");
        sb.AppendLine("            Copy-Item $dest (Join-Path $BinFolder $tool.File) -Force");
        sb.AppendLine("        }");
        sb.AppendLine("        'Archive' {");
        sb.AppendLine("            $target = Join-Path $ToolsRoot $tool.Id");
        sb.AppendLine("            New-Item -ItemType Directory -Force -Path $target | Out-Null");
        sb.AppendLine("            if ($tool.File -like '*.zip') {");
        sb.AppendLine("                Expand-Archive -Path $dest -DestinationPath $target -Force");
        sb.AppendLine("            } else {");
        sb.AppendLine("                tar -xf $dest -C $target");
        sb.AppendLine("            }");
        sb.AppendLine("            Get-ChildItem $target -Filter *.exe -Recurse | ForEach-Object {");
        sb.AppendLine("                Copy-Item $_.FullName (Join-Path $BinFolder $_.Name) -Force");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        'Installer' {");
        sb.AppendLine("            $sig = Get-AuthenticodeSignature -FilePath $dest");
        sb.AppendLine("            if ($sig.Status -ne 'Valid') {");
        sb.AppendLine("                Write-Warning (\"$($tool.Name): installer signature is '$($sig.Status)' - review before continuing.\")");
        sb.AppendLine("                $answer = Read-Host ('Launch this installer anyway? [y/N]')");
        sb.AppendLine("                if ($answer -notmatch '^[Yy]') { Write-Warning (\"Skipped $($tool.Name).\"); continue }");
        sb.AppendLine("            }");
        sb.AppendLine("            Write-Host '    Launching vendor installer - complete its wizard to finish.'");
        sb.AppendLine("            Start-Process -FilePath $dest -Wait");
        sb.AppendLine("        }");
        sb.AppendLine("        'Script' {");
        sb.AppendLine("            Write-Warning (\"$($tool.Name) is script-based - review it manually at: $dest\")");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Stage Tools\\bin on the user PATH (required for Binary/Archive CLIs)");
        sb.AppendLine("$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')");
        sb.AppendLine("if (($userPath -split ';') -notcontains $BinFolder) {");
        sb.AppendLine("    [Environment]::SetEnvironmentVariable('Path', \"$userPath;$BinFolder\", 'User')");
        sb.AppendLine("    Write-Host (\"Added $BinFolder to your user PATH - restart your terminal to pick it up.\")");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("Write-Host (\"Bootstrap complete: $($tools.Count) tools processed.\")");

        return sb.ToString();
    }
}
