using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using DevOpsToolsInstaller.Models;

namespace DevOpsToolsInstaller.Services;

public sealed record ShellCompletionInfo(
    string ToolId,
    string DisplayName,
    string PowerShellCommand,
    string BashCommand);

/// <summary>
/// Generates shell autocompletion snippets for DevOps command-line tools
/// and integrates them into the user's PowerShell profile.
/// </summary>
public static class ShellCompletionService
{
    private const string BlockHeader = "# >>> DevOpsToolsInstaller shell completion >>>";
    private const string BlockFooter = "# <<< DevOpsToolsInstaller shell completion <<<";

    private static readonly List<ShellCompletionInfo> SupportedTools = new()
    {
        new("kubectl", "kubectl", "if (Get-Command kubectl -ErrorAction SilentlyContinue) { kubectl completion powershell | Out-String | Invoke-Expression }", "which kubectl >/dev/null 2>&1 && source <(kubectl completion bash)"),
        new("helm", "Helm", "if (Get-Command helm -ErrorAction SilentlyContinue) { helm completion powershell | Out-String | Invoke-Expression }", "which helm >/dev/null 2>&1 && source <(helm completion bash)"),
        new("github-cli", "GitHub CLI (gh)", "if (Get-Command gh -ErrorAction SilentlyContinue) { gh completion -s powershell | Out-String | Invoke-Expression }", "which gh >/dev/null 2>&1 && eval \"$(gh completion -s bash)\""),
        new("gitlab-cli", "GitLab CLI (glab)", "if (Get-Command glab -ErrorAction SilentlyContinue) { glab completion -s powershell | Out-String | Invoke-Expression }", "which glab >/dev/null 2>&1 && eval \"$(glab completion -s bash)\""),
        new("k9s", "k9s", "if (Get-Command k9s -ErrorAction SilentlyContinue) { k9s completion powershell | Out-String | Invoke-Expression }", "which k9s >/dev/null 2>&1 && source <(k9s completion bash)"),
        new("kind", "kind", "if (Get-Command kind -ErrorAction SilentlyContinue) { kind completion powershell | Out-String | Invoke-Expression }", "which kind >/dev/null 2>&1 && source <(kind completion bash)"),
        new("minikube", "minikube", "if (Get-Command minikube -ErrorAction SilentlyContinue) { minikube completion powershell | Out-String | Invoke-Expression }", "which minikube >/dev/null 2>&1 && source <(minikube completion bash)"),
        new("argocd-cli", "ArgoCD CLI", "if (Get-Command argocd -ErrorAction SilentlyContinue) { argocd completion powershell | Out-String | Invoke-Expression }", "which argocd >/dev/null 2>&1 && source <(argocd completion bash)"),
        new("podman-desktop", "Podman", "if (Get-Command podman -ErrorAction SilentlyContinue) { podman completion powershell | Out-String | Invoke-Expression }", "which podman >/dev/null 2>&1 && source <(podman completion bash)"),
        new("docker-desktop", "Docker", "if (Get-Command docker -ErrorAction SilentlyContinue) { docker completion powershell | Out-String | Invoke-Expression }", "which docker >/dev/null 2>&1 && source <(docker completion bash)"),
        new("terraform", "Terraform", "# Run once in terminal: terraform -install-autocomplete", "complete -C terraform terraform"),
        new("opentofu", "OpenTofu", "# Run once in terminal: tofu -install-autocomplete", "complete -C tofu tofu")
    };

    /// <summary>
    /// Returns the list of tools that support autocompletion.
    /// </summary>
    public static IReadOnlyList<ShellCompletionInfo> GetAllSupportedTools() => SupportedTools;

    /// <summary>
    /// Generates a PowerShell profile script for the specified tools.
    /// </summary>
    public static string GeneratePowerShellSnippet(
        IEnumerable<ToolDefinition> tools,
        bool includeAllSupported = false)
    {
        var activeIds = new HashSet<string>(tools.Select(t => t.Id), StringComparer.OrdinalIgnoreCase);

        var targetItems = includeAllSupported
            ? SupportedTools
            : SupportedTools.Where(s => activeIds.Contains(s.ToolId)).ToList();

        if (targetItems.Count == 0 && !includeAllSupported)
        {
            // If none detected, fall back to all supported
            targetItems = SupportedTools;
        }

        var sb = new StringBuilder();
        sb.AppendLine(BlockHeader);
        sb.AppendLine("# Automatically generated by DevOps Tools Installer");
        sb.AppendLine($"# Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        foreach (var item in targetItems)
        {
            sb.AppendLine($"# {item.DisplayName}");
            sb.AppendLine(item.PowerShellCommand);
            sb.AppendLine();
        }

        sb.Append(BlockFooter);
        return sb.ToString();
    }

    /// <summary>
    /// Generates a Bash/Zsh snippet (useful for WSL2 or Git Bash).
    /// </summary>
    public static string GenerateBashSnippet(
        IEnumerable<ToolDefinition> tools,
        bool includeAllSupported = false)
    {
        var activeIds = new HashSet<string>(tools.Select(t => t.Id), StringComparer.OrdinalIgnoreCase);

        var targetItems = includeAllSupported
            ? SupportedTools
            : SupportedTools.Where(s => activeIds.Contains(s.ToolId)).ToList();

        if (targetItems.Count == 0 && !includeAllSupported)
        {
            targetItems = SupportedTools;
        }

        var sb = new StringBuilder();
        sb.AppendLine(BlockHeader);
        sb.AppendLine("# Add to ~/.bashrc or ~/.zshrc");
        sb.AppendLine($"# Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        foreach (var item in targetItems)
        {
            sb.AppendLine($"# {item.DisplayName}");
            sb.AppendLine(item.BashCommand);
            sb.AppendLine();
        }

        sb.Append(BlockFooter);
        return sb.ToString();
    }

    /// <summary>
    /// Gets the primary PowerShell user profile path ($PROFILE).
    /// </summary>
    public static string GetPowerShellProfilePath()
    {
        var docs = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);

        // Check modern PowerShell 7+ path first
        var ps7Path = Path.Combine(docs, "PowerShell", "Microsoft.PowerShell_profile.ps1");
        if (File.Exists(ps7Path)) return ps7Path;

        // Check WindowsPowerShell 5.1 path
        var ps5Path = Path.Combine(docs, "WindowsPowerShell", "Microsoft.PowerShell_profile.ps1");
        if (File.Exists(ps5Path)) return ps5Path;

        // Default to modern PowerShell path
        return ps7Path;
    }

    /// <summary>
    /// Checks whether the DevOpsToolsInstaller autocompletion block is present in the profile.
    /// </summary>
    public static bool IsSnippetInProfile()
    {
        var path = GetPowerShellProfilePath();
        if (!File.Exists(path)) return false;

        try
        {
            var content = File.ReadAllText(path);
            return content.Contains(BlockHeader);
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Appends or updates the autocompletion snippet in the user's PowerShell profile ($PROFILE).
    /// </summary>
    public static (bool Success, string Message) ApplyToPowerShellProfile(string snippet)
    {
        try
        {
            var profilePath = GetPowerShellProfilePath();
            var dir = Path.GetDirectoryName(profilePath);
            if (!string.IsNullOrEmpty(dir))
            {
                Directory.CreateDirectory(dir);
            }

            string existingContent = File.Exists(profilePath) ? File.ReadAllText(profilePath) : string.Empty;

            string newContent;
            int startIndex = existingContent.IndexOf(BlockHeader, StringComparison.Ordinal);
            int endIndex = existingContent.IndexOf(BlockFooter, StringComparison.Ordinal);

            if (startIndex >= 0 && endIndex >= 0 && endIndex >= startIndex)
            {
                // Replace existing block
                endIndex += BlockFooter.Length;
                newContent = existingContent[..startIndex] + snippet + existingContent[endIndex..];
            }
            else
            {
                // Append
                newContent = string.IsNullOrWhiteSpace(existingContent)
                    ? snippet + Environment.NewLine
                    : existingContent.TrimEnd() + Environment.NewLine + Environment.NewLine + snippet + Environment.NewLine;
            }

            File.WriteAllText(profilePath, newContent, Encoding.UTF8);
            return (true, $"Autocompletion successfully saved to {profilePath}. Restart your terminal to activate.");
        }
        catch (Exception ex)
        {
            return (false, $"Failed to update PowerShell profile: {ex.Message}");
        }
    }
}
