# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: NotHarshhaa.DevOpsToolsInstaller
PackageVersion: 2.5.0
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-21
AppsAndFeaturesEntries:
  - DisplayName: DevOps Tools Installer
    Publisher: NotHarshhaa
    DisplayVersion: 2.5.0
    ProductCode: '{D3V0P5-T00L5-1N5T4LL3R-2026-V2}_is1'
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/NotHarshhaa/DevOpsToolsInstaller/releases/download/v2.5.0/DevOpsToolsInstaller_x64_Setup.exe
    InstallerSha256: AB0419E0BA74CFF44CEF3D3655A5993E95E921494C2F964836A33CCFDEF8B98A
ManifestType: installer
ManifestVersion: 1.6.0
